on:
  workflow_call:
    inputs:
      extensionName:
        description: 'Your extension name'
        required: true
        type: string
      shopwareVersion:
        required: false
        type: string
        default: 'trunk'
jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Shopware
        uses: FriendsOfShopware/setup-shopware@main
        with:
          shopware-version: ${{ inputs.shopwareVersion }}
          php-version: 8.2
          php-extensions: pcov
      - name: Clone Extension
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ inputs.extensionName }}
      - name: Run PHPUnit
        working-directory: custom/plugins/${{ inputs.extensionName }}
        run: ${{ github.workspace }}/vendor/bin/phpunit --coverage-clover ${{ github.workspace }}/coverage.xml
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ${{ github.workspace }}/clover.xml
